Bug #51316 up: Convert u-upgrade to Python 3
App-Center is broken and must be disabled with `--disable-app-updates`:
> Checking for app updates:                               Traceback in univention-upgrade:
> Traceback (most recent call last):
>   File "./python/univention-upgrade", line 442, in do_update
>     update_available = performUpdate(options, checkForUpdates=options.check, silent=False)
>   File "./python/univention-upgrade", line 139, in performUpdate
>     if func(options, checkForUpdates, silent):
>   File "./python/univention-upgrade", line 271, in do_app_updates
>     app_upgrade_search.call()
>   File "/usr/lib/python3/dist-packages/univention/appcenter/actions/__init__.py", line 174, in call
>     return obj.call_with_namespace(namespace)
>   File "/usr/lib/python3/dist-packages/univention/appcenter/actions/__init__.py", line 180, in call_with_namespace
>     result = self.main(namespace)
>   File "/usr/lib/python3/dist-packages/univention/appcenter/actions/upgrade_search.py", line 52, in main
>     get_action('update').call()
>   File "/usr/lib/python3/dist-packages/univention/appcenter/actions/__init__.py", line 174, in call
>     return obj.call_with_namespace(namespace)
>   File "/usr/lib/python3/dist-packages/univention/appcenter/actions/__init__.py", line 180, in call_with_namespace
>     result = self.main(namespace)
>   File "/usr/lib/python3/dist-packages/univention/appcenter/actions/update.py", line 77, in main
>     if self._download_supra_files(appcenter_cache):
>   File "/usr/lib/python3/dist-packages/univention/appcenter/actions/update.py", line 145, in _download_supra_files
>     return self._download_files(appcenter_cache, ['app-categories.ini', 'rating.ini', 'license_types.ini', 'ucs.ini', 'suggestions.json'])
>   File "/usr/lib/python3/dist-packages/univention/appcenter/actions/update.py", line 152, in _download_files
>     present_etags = self._get_etags(etags_file)
>   File "/usr/lib/python3/dist-packages/univention/appcenter/actions/update.py", line 129, in _get_etags
>     fname, etag = line.split('\t')
> TypeError: a bytes-like object is required, not 'str'